// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTfoq0YKdOvk7Dky2TyikggIL2wZyKAw',
    appId: '1:640212750326:web:d41fc5642acfe6525a41d7',
    messagingSenderId: '640212750326',
    projectId: 'shorouk-7d7a1',
    authDomain: 'shorouk-7d7a1.firebaseapp.com',
    storageBucket: 'shorouk-7d7a1.appspot.com',
    measurementId: 'G-CWCJWBH0WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5X30PS_2GR-a-JDGkOCltJP9GqS1RfM',
    appId: '1:640212750326:android:1f9093c032437bde5a41d7',
    messagingSenderId: '640212750326',
    projectId: 'shorouk-7d7a1',
    storageBucket: 'shorouk-7d7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvQHHIjSLft6AtENn9NFuX3rCpWf6xs8',
    appId: '1:640212750326:ios:2e8ebe575ab1abb75a41d7',
    messagingSenderId: '640212750326',
    projectId: 'shorouk-7d7a1',
    storageBucket: 'shorouk-7d7a1.appspot.com',
    iosBundleId: 'com.example.shorouk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvQHHIjSLft6AtENn9NFuX3rCpWf6xs8',
    appId: '1:640212750326:ios:2e8ebe575ab1abb75a41d7',
    messagingSenderId: '640212750326',
    projectId: 'shorouk-7d7a1',
    storageBucket: 'shorouk-7d7a1.appspot.com',
    iosBundleId: 'com.example.shorouk',
  );
}
